<h1 class="titre_add_post">Nouvel article</h1>
<section class="nouvel_article">
	<h2><i class="fas fa-pencil-alt"></i> Rédiger un nouvel article</h2>
	<form action="add_post.php" method="Post">
		<fieldset>
			<legend class="add_post_color"><i class="far fa-sticky-note"></i> Nouvel article</legend>
			<ul class="ul">
				<li>
					<label for="Title">Titre :</label><br>
					<input name="Title" type="text" id="Title" />
				</li>
				<li>
					<label class="contents" for="contents">Article :</label><br>
					<textarea id="contents" name="contents" rows="15" cols="130"></textarea>
				</li>
				<li>
					<label for="author">Auteur :
					<select name="author" id="author" for="author">
						<?php foreach ($AuthorResult as $author): ?>
						<option value="<?= Htmlspecialchars($author['Id']) ?>"><?= Htmlspecialchars($author['FirstName']) ?> <?= Htmlspecialchars($author['LastName']) ?></option>
						<?php endforeach ?>
					</select>
					</label>
				</li>
				<li>
					<label for="category">Catégorie :
					<select name="category" id="category" for="category">
						<?php foreach ($CategoryResult as $category): ?>
						<option value="<?= intval($category['Id']) ?>"><?= Htmlspecialchars($category['Name']) ?></option>
						<?php endforeach ?>
					</select>
					</label>
				</li>
				<li class="boutton">
					<button class="firstbutton" type="submit">Enregistrer</button>
					<button class="buttoneffacer" value="index.php">Annuler</button>
				</li>
			</ul>
			
			
		</fieldset>
	</form>
</section>