<h2>Connexion</h2>

    <form class="connexion_membres" action="connexion_membres.php" method="POST">
        <p class="form-group">
            <label for="pseudo">Pseudo ?</label>
            <input type="text" name="pseudo" class="form-control" />
        </p>
        <p class="form-group">
            <label for="pass"> Mot de passe ? </label>
            <input type="password" name="pass" class="form-control" />
        </p>
        <p class="form-group">
            <label for="connexion_auto"> Connexion automatique </label>
            <input type="checkbox" name="connexion_auto" class="form-control" />
        </p>
        <p>
            <input type="submit" value="Se connecter" class="btn btn-primary mb-2" />
        </p>
    </form>