<h2>Inscription</h2>

    <form class="membres" action="news_membres.php" method="POST">
        <p class="form-group">
            <label for="pseudo">Pseudo ?</label>
            <input type="text" name="pseudo" class="form-control" />
        </p>
        <p class="form-group">
            <label for="pass"> Mot de passe ? </label>
            <input type="password" name="pass" class="form-control" />
        </p>
        <p class="form-group">
            <label for="repeatpassword"> Confirmer le mot de passe</label>
            <input type="password" name="repeatpassword" class="form-control"/>
        </p>
        <p class="form-group">
            <label for="email"> Adresse Email ?</label>
            <input type="email" name="email" class="form-control" />
        </p>
        <p>
            <input type="submit" value="Enregistrer" class="btn btn-primary mb-2" />
        </p>
    </form>